%% Independent sample t-test
sFilesB = db_template('importfile');

jj = 1; conlab = '04'; sFiles_in = sFiles_4;
% Process: FT t-test unequal fdr [1000ms]          H0:(A=B), H1:(A<>B)
bst_process('CallProcess', 'process_ft_sourcestatistics_edit', sFiles_in, sFilesB, ...
    'timewindow',     [1, 1], ...
    'scoutsel',       {}, ...
    'scoutfunc',      1, ...  % Mean
    'isabs',          0, ...
    'avgtime',        0, ...
    'randomizations', 10000, ...
    'statistictype',  1, ...  % Independent t-test
    'tail',           'one+', ...  % Two-tailed
    'correctiontype', 4, ...  % fdr
    'minnbchan',      0, ...
    'Comment', ['FT ttest, ', num2str(length(sFiles_in)),' files, cond: ', conlab], ...
    'clusteralpha',   0.05);


jj = 1; conlab = '08'; sFiles_in = sFiles_8;
% Process: FT t-test unequal fdr [1000ms]          H0:(A=B), H1:(A<>B)
bst_process('CallProcess', 'process_ft_sourcestatistics_edit', sFiles_in, sFilesB, ...
    'timewindow',     [1, 1], ...
    'scoutsel',       {}, ...
    'scoutfunc',      1, ...  % Mean
    'isabs',          0, ...
    'avgtime',        0, ...
    'randomizations', 10000, ...
    'statistictype',  1, ...  % Independent t-test
    'tail',           'one+', ...  % Two-tailed
    'correctiontype', 4, ...  % fdr
    'minnbchan',      0, ...
    'Comment', ['FT ttest, ', num2str(length(sFiles_in)),' files, cond: ', conlab], ...
    'clusteralpha',   0.05);


jj = 1; conlab = '16'; sFiles_in = sFiles_16;
% Process: FT t-test unequal fdr [1000ms]          H0:(A=B), H1:(A<>B)
bst_process('CallProcess', 'process_ft_sourcestatistics_edit', sFiles_in, sFilesB, ...
    'timewindow',     [1, 1], ...
    'scoutsel',       {}, ...
    'scoutfunc',      1, ...  % Mean
    'isabs',          0, ...
    'avgtime',        0, ...
    'randomizations', 10000, ...
    'statistictype',  1, ...  % Independent t-test
    'tail',           'one+', ...  % Two-tailed
    'correctiontype', 4, ...  % fdr
    'minnbchan',      0, ...
    'Comment', ['FT ttest, ', num2str(length(sFiles_in)),' files, cond: ', conlab], ...
    'clusteralpha',   0.05);



jj = 1; conlab = '32'; sFiles_in = sFiles_32;
% Process: FT t-test unequal fdr [1000ms]          H0:(A=B), H1:(A<>B)
bst_process('CallProcess', 'process_ft_sourcestatistics_edit', sFiles_in, sFilesB, ...
    'timewindow',     [1, 1], ...
    'scoutsel',       {}, ...
    'scoutfunc',      1, ...  % Mean
    'isabs',          0, ...
    'avgtime',        0, ...
    'randomizations', 10000, ...
    'statistictype',  1, ...  % Independent t-test
    'tail',           'one+', ...  % Two-tailed
    'correctiontype', 4, ...  % fdr
    'minnbchan',      0, ...
    'Comment', ['FT ttest, ', num2str(length(sFiles_in)),' files, cond: ', conlab], ...
    'clusteralpha',   0.05);


%% Dependent sample t-test
sFiles_A = sFiles_4; conlab1 = '4';
sFiles_B = sFiles_8; conlab2 = '8';
% Process: FT t-test paired fdr [1000ms]          H0:(A=B), H1:(A<>B)
bst_process('CallProcess', 'process_ft_sourcestatistics_edit', sFiles_A, sFiles_B, ...
    'timewindow',     [1, 1], ...
    'scoutsel',       {}, ...
    'scoutfunc',      1, ...  % Mean
    'isabs',          0, ...
    'avgtime',        0, ...
    'randomizations', 1000, ...
    'statistictype',  2, ...  % Paired t-test
    'tail',           'one-', ...  % One-tailed (+)
    'correctiontype', 5, ...  % max
    'minnbchan',      0, ...
    'Comment', ['FT ttest, ', num2str(length(sFiles_A)),' files, ',conlab1, ' vs ', conlab2], ...
    'clusteralpha',   0.05);
%     'tail',           'two', ...  % Two-tailed
%     'correctiontype', 4, ...  % fdr


sFiles_A = sFiles_16; conlab1 = '16';
sFiles_B = sFiles_32; conlab2 = '32';
% Process: FT t-test paired fdr [1000ms]          H0:(A=B), H1:(A<>B)
bst_process('CallProcess', 'process_ft_sourcestatistics_edit', sFiles_A, sFiles_B, ...
    'timewindow',     [1, 1], ...
    'scoutsel',       {}, ...
    'scoutfunc',      1, ...  % Mean
    'isabs',          0, ...
    'avgtime',        0, ...
    'randomizations', 1000, ...
    'statistictype',  2, ...  % Paired t-test
    'tail',           'one-', ...  % One-tailed (+)
    'correctiontype', 5, ...  % max
    'minnbchan',      0, ...
    'Comment', ['FT ttest, ', num2str(length(sFiles_A)),' files, ',conlab1, ' vs ', conlab2], ...
    'clusteralpha',   0.05);
%     'tail',           'two', ...  % Two-tailed
%     'correctiontype', 4, ...  % fdr


sFiles_A = sFiles_8; conlab1 = '8';
sFiles_B = sFiles_32; conlab2 = '32';
% Process: FT t-test paired fdr [1000ms]          H0:(A=B), H1:(A<>B)
bst_process('CallProcess', 'process_ft_sourcestatistics_edit', sFiles_A, sFiles_B, ...
    'timewindow',     [1, 1], ...
    'scoutsel',       {}, ...
    'scoutfunc',      1, ...  % Mean
    'isabs',          0, ...
    'avgtime',        0, ...
    'randomizations', 1000, ...
    'statistictype',  2, ...  % Paired t-test
    'tail',           'one-', ...  % One-tailed (+)
    'correctiontype', 5, ...  % max
    'minnbchan',      0, ...
    'Comment', ['FT ttest, ', num2str(length(sFiles_A)),' files, ',conlab1, ' vs ', conlab2], ...
    'clusteralpha',   0.05);
%     'tail',           'two', ...  % Two-tailed
%     'correctiontype', 4, ...  % fdr


sFiles_A = sFiles_4; conlab1 = '4';
sFiles_B = sFiles_16; conlab2 = '16';
% Process: FT t-test paired fdr [1000ms]          H0:(A=B), H1:(A<>B)
bst_process('CallProcess', 'process_ft_sourcestatistics_edit', sFiles_A, sFiles_B, ...
    'timewindow',     [1, 1], ...
    'scoutsel',       {}, ...
    'scoutfunc',      1, ...  % Mean
    'isabs',          0, ...
    'avgtime',        0, ...
    'randomizations', 1000, ...
    'statistictype',  2, ...  % Paired t-test
    'tail',           'one-', ...  % One-tailed (+)
    'correctiontype', 5, ...  % max
    'minnbchan',      0, ...
    'Comment', ['FT ttest, ', num2str(length(sFiles_A)),' files, ',conlab1, ' vs ', conlab2], ...
    'clusteralpha',   0.05);
%     'tail',           'two', ...  % Two-tailed
%     'correctiontype', 4, ...  % fdr


sFiles_A = sFiles_32; conlab1 = '32';
sFiles_B = sFiles_16; conlab2 = '16';
% Process: FT t-test paired fdr [1000ms]          H0:(A=B), H1:(A<>B)
bst_process('CallProcess', 'process_ft_sourcestatistics_edit', sFiles_A, sFiles_B, ...
    'timewindow',     [1, 1], ...
    'scoutsel',       {}, ...
    'scoutfunc',      1, ...  % Mean
    'isabs',          0, ...
    'avgtime',        0, ...
    'randomizations', 1000, ...
    'statistictype',  2, ...  % Paired t-test
    'tail',           'one-', ...  % One-tailed (+)
    'correctiontype', 5, ...  % max
    'minnbchan',      0, ...
    'Comment', ['FT ttest, ', num2str(length(sFiles_A)),' files, ',conlab1, ' vs ', conlab2], ...
    'clusteralpha',   0.05);
%     'tail',           'two', ...  % Two-tailed
%     'correctiontype', 4, ...  % fdr


sFiles_A = sFiles_4; conlab1 = '04';
sFiles_B = sFiles_32; conlab2 = '32';
% Process: FT t-test paired fdr [1000ms]          H0:(A=B), H1:(A<>B)
bst_process('CallProcess', 'process_ft_sourcestatistics_edit', sFiles_A, sFiles_B, ...
    'timewindow',     [1, 1], ...
    'scoutsel',       {}, ...
    'scoutfunc',      1, ...  % Mean
    'isabs',          0, ...
    'avgtime',        0, ...
    'randomizations', 1000, ...
    'statistictype',  2, ...  % Paired t-test
    'tail',           'one-', ...  % One-tailed (+)
    'correctiontype', 5, ...  % max
    'minnbchan',      0, ...
    'Comment', ['FT ttest, ', num2str(length(sFiles_A)),' files, ',conlab1, ' vs ', conlab2], ...
    'clusteralpha',   0.05);
%     'tail',           'two', ...  % Two-tailed
%     'correctiontype', 4, ...  % fdr


sFiles_A = sFiles_8; conlab1 = '08';
sFiles_B = sFiles_16; conlab2 = '16';
% Process: FT t-test paired fdr [1000ms]          H0:(A=B), H1:(A<>B)
bst_process('CallProcess', 'process_ft_sourcestatistics_edit', sFiles_A, sFiles_B, ...
    'timewindow',     [1, 1], ...
    'scoutsel',       {}, ...
    'scoutfunc',      1, ...  % Mean
    'isabs',          0, ...
    'avgtime',        0, ...
    'randomizations', 1000, ...
    'statistictype',  2, ...  % Paired t-test
    'tail',           'one-', ...  % One-tailed (+)
    'correctiontype', 5, ...  % max
    'minnbchan',      0, ...
    'Comment', ['FT ttest, ', num2str(length(sFiles_A)),' files, ',conlab1, ' vs ', conlab2], ...
    'clusteralpha',   0.05);
%     'tail',           'two', ...  % Two-tailed
%     'correctiontype', 4, ...  % fdr


%% RUN1 vs RUN2
sFiles_A = [sFiles_4(1:2:28), sFiles_8(1:2:28), sFiles_16(1:2:28), sFiles_32(1:2:28)];
sFiles_B = [sFiles_4(2:2:28), sFiles_8(2:2:28), sFiles_16(2:2:28), sFiles_32(2:2:28)];
% conlab1 = '4';
% sFiles_B = sFiles_8; conlab2 = '8';
% Process: FT t-test paired fdr [1000ms]          H0:(A=B), H1:(A<>B)
bst_process('CallProcess', 'process_ft_sourcestatistics_edit', sFiles_A, sFiles_B, ...
    'timewindow',     [1, 1], ...
    'scoutsel',       {}, ...
    'scoutfunc',      1, ...  % Mean
    'isabs',          0, ...
    'avgtime',        0, ...
    'randomizations', 10000, ...
    'statistictype',  2, ...  % Paired t-test
    'tail',           'two', ...  % One-tailed (+)
    'correctiontype', 5, ...  % max
    'minnbchan',      0, ...
    'Comment', ['FT ttest, ', num2str(length(sFiles_A)),' files, ', 'run1 vs run2'], ...
    'clusteralpha',   0.05);

%% RUN 1 
sFilesA = [sFiles_4(1:2:28), sFiles_8(1:2:28), sFiles_16(1:2:28), sFiles_32(1:2:28)];
sFilesB = db_template('importfile');

bst_process('CallProcess', 'process_ft_sourcestatistics_edit', sFilesA, sFilesB, ...
    'timewindow',     [1, 1], ...
    'scoutsel',       {}, ...
    'scoutfunc',      1, ...  % Mean
    'isabs',          0, ...
    'avgtime',        0, ...
    'randomizations', 10000, ...
    'statistictype',  1, ...  % Independent t-test
    'tail',           'one+', ...  % Two-tailed
    'correctiontype', 4, ...  % fdr
    'minnbchan',      0, ...
    'Comment', ['FT ttest, ', num2str(length(sFilesA)),' files, run1 all 4 tasks'], ...
    'clusteralpha',   0.05);

%% RUN 2 
sFilesA = [sFiles_4(2:2:28), sFiles_8(2:2:28), sFiles_16(2:2:28), sFiles_32(2:2:28)];
sFilesB = db_template('importfile');

bst_process('CallProcess', 'process_ft_sourcestatistics_edit', sFilesA, sFilesB, ...
    'timewindow',     [1, 1], ...
    'scoutsel',       {}, ...
    'scoutfunc',      1, ...  % Mean
    'isabs',          0, ...
    'avgtime',        0, ...
    'randomizations', 10000, ...
    'statistictype',  1, ...  % Independent t-test
    'tail',           'one+', ...  % Two-tailed
    'correctiontype', 4, ...  % fdr
    'minnbchan',      0, ...
    'Comment', ['FT ttest, ', num2str(length(sFilesA)),' files, run2 all 4 tasks'], ...
    'clusteralpha',   0.05);



%%